name: Build TCG Assistant APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Generate native code
      run: npx expo eject --no-install
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Debug APK
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' || github.event_name == 'push'
      run: |
        cd android
        ./gradlew assembleDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Build Release APK
      if: github.event.inputs.build_type == 'release'
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload Debug APK
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == '' || github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: tcg-assistant-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      if: github.event.inputs.build_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: tcg-assistant-release
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: TCG Assistant v${{ github.run_number }}
        body: |
          ## TCG助手 APK 構建
          
          ### 構建信息
          - 構建編號: ${{ github.run_number }}
          - 提交: ${{ github.sha }}
          - 分支: ${{ github.ref }}
          
          ### 下載
          - Debug APK: 請在Artifacts中下載
          
          ### 安裝說明
          1. 下載APK文件
          2. 在Android設備上啟用"未知來源"安裝
          3. 安裝APK文件
          4. 測試應用程序功能
        draft: false
        prerelease: false
